name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
   { pattern = "docker.cyg.ip-ddns.com", custom_domain = true },
   { pattern = "quay.cyg.ip-ddns.com", custom_domain = true },
   { pattern = "gcr.cyg.ip-ddns.com", custom_domain = true },
   { pattern = "k8s-gcr.cyg.ip-ddns.com", custom_domain = true },
   { pattern = "k8s.cyg.ip-ddns.com", custom_domain = true },
   { pattern = "ghcr.cyg.ip-ddns.com", custom_domain = true },
   { pattern = "cloudsmith.cyg.ip-ddns.com", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.cyg.ip-ddns.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
